### ISSUE TITLE
Error from resvgjs: Unexpected character '�' 

### ISSUE THREAD

**Issue by imalbert** [shepherdjerred/astro-opengraph-images#75]
# Bug
This error appears during build

```zsh
Result (51 files): 
- 0 errors
- 0 warnings
- 59 hints

(node:75736) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
06:22:51 [vite] Re-optimizing dependencies because vite config has changed
06:22:51 [types] Generated 210ms
06:22:51 [build] output: "static"
06:22:51 [build] directory: /Users/-/projects/client/-/dist/
06:22:51 [build] Collecting build info...
06:22:51 [build] ✓ Completed in 242ms.
06:22:51 [build] Building static entrypoints...
06:22:52 [ERROR] [vite] x Build failed in 1.06s
[commonjs--resolver] node_modules/.pnpm/@resvg+resvg-js-darwin-arm64@2.6.2/node_modules/@resvg/resvg-js-darwin-arm64/resvgjs.darwin-arm64.node (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
file: /Users/-/projects/client/-/node_modules/.pnpm/@resvg+resvg-js@2.6.2/node_modules/@resvg/resvg-js/index.js:1:0

1: ����
       ���__TEXT�2�__text...
   ^
2: 
   P���58q�݋O<7�M=�.��2 ...
3: �R�����}�@���        KP�1@�k�
                                        �cD�JQ?
                                               ��T�ik8�Q?*qT
                                                            ���T���T q���TD
                                                                           ���...

  Stack trace:
    at getRollupError (file:///Users/-/projects/client/-/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at convertNode (file:///Users/-/projects/client/-/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:13181:10)
    at Module.setSource (file:///Users/-/projects/client/-/node_modules/.pnpm/rollup@){e=e.getSelection();var l=t.textContent.length,u=Math.min(r.start,l);r=r.end===void 0?u:Math.min(r.end,l),!e.extend&&u>r&&(l=r,r=u,u=l),l=ti(t,u);var o=ti(t,r);l&&o&&(e.rangeCount!==1||e.anchorNode!==l.node||e.anchorOffset!==l.offset||e.focusNode!==o.node||e.focusOffset!==o.offset)&&(n=n.createRange(),n.setStart(l.node,l.offset),e.removeAllRanges(),u>r?(e.addRange(n),e.extend(o.node,o.offset)):(n.setEnd(o.node,o.offset),e.addRange(n)))}}for(n=[],e=t;e=e.parentNode;)e.nodeType===1&&n.push({element:e,left:e.scrollLeft,top:e.scrollTop});for(typeof t.focus=="function"&&t.focus(),t=0;t<n.length;t++)e=n[t],e.element.scrollLeft=e.left,e.element.scrollTop=e.top}}var zf=He&&"documentMode"in document&&11>=document.documentMode,In=null,iu=null,_t=null,su=!1;function ri(e,n,t){var r=t.window===t?t.document:t.nodeType===9?t:t.ownerDocument;su||In==null||In!==zr(r)||(r=In,"selectionStart"in r&&eo(r)?r={start:r.selectionStart,end:r.selectionEnd}:(r=(r.ownerDocument&&r.ownerDocument.defaultView||window).getSelection(),r
```

# Setup

```mjs
// astro.config.mjs
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import tailwind from "@astrojs/tailwind";
import opengraphImages, { presets } from "astro-opengraph-images";
import react from "@astrojs/react";

// https://astro.build/config
export default defineConfig({
  site: "https://hcaeb.com",
  integrations: [
    mdx(),
    tailwind({
      applyBaseStyles: false,
    }),
    opengraphImages({
      options: {
        fonts: [
          {
            name: "Roboto",
            weight: 400,
            style: "normal",
            data: fs.readFileSync(
              "node_modules/@fontsource/roboto/files/roboto-latin-400-normal.woff"
            ),
          },
        ],
      },
      render: presets.blackAndWhite,
    }),
    react(),
  ],
});

```

```
const ogImageURL = getImagePath({ url: Astro.url, site: Astro.site });

    ...
    <meta property="og:type" content="website" />
    <meta property="og:url" content={permalink} />
    <meta property="og:title" content={completeTitle} />
    <meta property="og:description" content={description} />
    <meta property="og:image" content={ogImageURL} />
    <SEO
      openGraph={
        {
          basic: {
            title: title,
            type: "website",
            image: ogImageURL,
            url: Astro.url,
          },
          optional: {
            description: "My page description",
          },
        }
      }
    />
```

I hope you can help me with this one. Thank you!

**Comment by shepherdjerred** [comment]
Hi!

This doesn't seem to be an issue with this library. I'd look around at the resvg project.

**Comment by felixicaza** [comment]
With PNPM configure the option `shamefully-hoist=true` in `.npmrc` or use with CLI flag. This is because PNPM does not generate a dependency structure like NPM or Yarn, reference: https://pnpm.io/cli/install#--shamefully-hoist
